import type { AppProps } from 'next/app'
import Head from 'next/head'
import '../styles/globals.css'
import '@mui/material/styles';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Deslocamento App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Component {...pageProps} />
    </div>
  )
}
